services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - keycloak_h2_data:/opt/keycloak/data/
    restart: always

volumes:
  keycloak_h2_data:
